"use client"

import { useState } from "react"
import { Check, X, FileText, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { approveWorkflow, rejectWorkflow } from "@/app/actions/temporal"

interface ApprovalCardProps {
  workflowId?: string
  title?: string
  description?: string
  content?: string
  prompt?: string // The original prompt
}

export function ApprovalCard({ 
  workflowId = "demo-workflow-id", 
  title = "Review Draft: Q1 Market Analysis",
  description = "Generated by Business Auditor Agent • 2m ago",
  content = "DRAFT CONTENT for Q1 Market Analysis... [Review Required]\n\nSummary of Key Findings:\n1. Competitor A has increased ad spend by 15%.\n2. New regulatory framework introduced in EU.",
  prompt = "Generate a market analysis for Q1 targeting European competitors."
}: ApprovalCardProps) {
  const [status, setStatus] = useState<"pending" | "approved" | "rejected">("pending")
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [correction, setCorrection] = useState("")

  const saveFeedback = async (rating: number = 5) => {
    if (!correction) return;
    try {
      await fetch('/api/ai/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt,
          completion: content,
          correction,
          rating,
          metadata: { workflowId }
        })
      });
    } catch (err) {
      console.error("Failed to save feedback", err);
    }
  }

  const handleApprove = async () => {
    setIsSubmitting(true)
    if (correction) await saveFeedback(5)
    const result = await approveWorkflow(workflowId)
    setIsSubmitting(false)
    
    if (result.success) {
      setStatus("approved")
    } else {
      alert("Failed to send approval signal.")
    }
  }

  const handleReject = async () => {
    if (!correction) {
      alert("Por favor, describe los cambios necesarios antes de rechazar.");
      return;
    }
    setIsSubmitting(true)
    await saveFeedback(1)
    const result = await rejectWorkflow(workflowId)
    setIsSubmitting(false)
    
    if (result.success) {
      setStatus("rejected")
    } else {
      alert("Failed to send rejection signal.")
    }
  }

  if (status === "approved") {
    return (
      <Card className="bg-emerald-500/10 border-emerald-500/20">
        <CardContent className="pt-6 flex flex-col items-center justify-center text-emerald-500">
            <Check className="h-8 w-8 mb-2" />
            <p className="font-semibold">Contenido Aprobado y Publicado</p>
        </CardContent>
      </Card>
    )
  }

  if (status === "rejected") {
    return (
        <Card className="bg-red-500/10 border-red-500/20">
        <CardContent className="pt-6 flex flex-col items-center justify-center text-red-500">
            <X className="h-8 w-8 mb-2" />
            <p className="font-semibold">Contenido enviado a revisión</p>
            <p className="text-xs mt-2 opacity-70">Tu corrección ha sido guardada para mejorar el modelo.</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="w-full shadow-2xl border-white/10 bg-slate-900 overflow-hidden">
      <CardHeader className="border-b border-white/5">
        <div className="flex items-center space-x-3">
            <div className="p-2 bg-blue-500/20 rounded-lg">
                <FileText className="h-5 w-5 text-blue-500" />
            </div>
            <div>
                <CardTitle className="text-white text-lg">{title}</CardTitle>
                <CardDescription className="text-slate-400">{description}</CardDescription>
            </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 pt-6">
        <div className="p-4 bg-slate-950 rounded-lg text-sm font-mono whitespace-pre-wrap border border-white/5 text-slate-300">
          {content}
        </div>

        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Correcciones o Instrucciones</label>
          <Textarea 
            placeholder="¿Qué debería cambiar la IA? (Ej: El tono es muy informal, elimina el punto 3...)"
            value={correction}
            onChange={(e) => setCorrection(e.target.value)}
            className="bg-slate-950 border-white/10 text-white placeholder:text-slate-600 focus:ring-emerald-500/50"
          />
        </div>
      </CardContent>
      <CardFooter className="flex justify-between gap-4 bg-white/5 p-6 mt-4">
        <Button 
          variant="ghost" 
          className="flex-1 text-slate-400 hover:text-red-400 hover:bg-red-400/10 border border-white/10" 
          onClick={handleReject}
          disabled={isSubmitting}
        >
          {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <X className="mr-2 h-4 w-4" />}
          Rechazar y Corregir
        </Button>
        <Button 
          className="flex-1 bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white shadow-lg shadow-emerald-500/20" 
          onClick={handleApprove}
          disabled={isSubmitting}
        >
          {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Check className="mr-2 h-4 w-4" />}
          Aprobar y Publicar
        </Button>
      </CardFooter>
    </Card>
  )
}
